### ISSUE TITLE
Feature: A Mostro can define which fiat currencies can be exchanged on it.

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro#478]
A Mostro operator should be able to decide which fiat currencies can be exchanged on their Mostro, so as not to have to deal with disputes or any issues associated with orders using a fiat currency that they has no experience with.
By default, any currency should be allowed, but if the admin decides to set a certain number of currencies, they should be able to do so.

Users should be able to know which currencies a Mostro allows, so perhaps that information could be added to the event of [Mostro Instance Status](https://mostro.network/protocol/other_events.html#mostro-instance-status)

**Comment by arkanoider** [comment]
Will take this in charge!

Could be that admin will have a new field in `settings.toml` like : 
```toml
[mostro]
# Mostro Fee
fee = 0
# Max routing fee that we want to pay to the network, 0.001 = 0.1%
max_routing_fee = 0.001
# Max order amount (sats)
max_order_amount = 1000000
# Minimum amount for a payment in satoshis
min_payment_amount = 100
# Expiration order hours
expiration_hours = 24
# Max expiration days for an order
max_expiration_days = 15
# Expiration of pending orders
expiration_seconds = 900
# User rate events scheduled time interval
user_rates_sent_interval_seconds = 3600
# Relay list event time interval
publish_relays_interval = 60
# Requested POW
pow = 0
# Publish mostro info interval
publish_mostro_info_interval = 300
#Accpeted currencies
currencies = ['EUR', 'ARS', 'USD']
```

in case of empty value, all values are accepted.

Mostro info message will propagate the info on Nostr.

Sounds good @Catrya @grunch ?
